### ISSUE TITLE
Excellent language

### ISSUE THREAD

**Issue by Gavlooth** [bakpakin/dst#1]
`Are` you planning in releasing you project ? It is very interesting, I would like to toy with it.
Even without documentation is quite easy to  write some code. Reduce took like a minute.

(defn fold [f s]
 "folds a sequence onto function f" 
 (var tail-tail (tail (tail s)) )
 (if (empty? tail-tail)
  (f (head s) (head (tail s)))
  (fold f (cons  (f (head s)  (head (tail s))) tail-tail))))

**Comment by bakpakin** [comment]
> Are you planning in releasing you project ?

It depends on what you mean by releasing. The code is already public and anyone can download and build. Perhaps you mean prebuilt binaries with a version number?

Eventually. It is not production ready yet, but also I would like the ability hack around with core ideas for a bit longer and add in a few very useful features. 

There is a lot to do though, especially in the way of writing documentation. There is probably about 12k lines of C code and over a hundred dst functions that aren't (well) documented. The dst functions especially should be documented somewhere.ability hack around with core ideas for a bit longer and add in a few very useful features. 

There is a lot to do though, especially in the way of writing documentation. There is probably about 12k lines of C code and over a hundred dst functions that aren't (well) documented. The dst functions especially should be documented somewhere.

**Comment by Gavlooth** [comment]
Yeah I see. Is not about binaries, more about documentetion and stable futures. Regardless, good job ,😃

**Comment by Gavlooth** [comment]
Also I could probably contribute by writing some functions if you are interested, and you think my coding style is ok

**Comment by bakpakin** [comment]
Yes just submit pull requests. The coding style for dst source is not really defined well yet, just generally lisp like. For C, try to use 4 spaces for indentation, spaces after commas and between operators, K & R style braces, and its ok to drop brackets when appropriate.

**Comment by bakpakin** [comment]
I don't really have a great roadmap for what functions to add to dst, but I have been porting some of clojure's combinators and functions in the core namespace.

**Comment by Gavlooth** [comment]
Cool. I haven't written in C for age but I know my way around in Clojure code. Thanks for the info
